import { selectOption } from './select.js';
import { translate, shortMonth } from '../../src/i18n/index.js';
const tr = (key: string, params?: Record<string, string | number>) => translate('zh', key, params);
import { test, expect } from '@playwright/test';

test('manual entry, totals, column filtering, splits and reload', async ({ page }) => {
  const errors: string[] = []; page.on('pageerror', (error) => errors.push(error.message));
  await page.goto('/?month=2026-08');
  await page.getByRole('button', { name: tr("Add transaction") }).click();
  await page.getByLabel(tr("Account name")).fill('Browser test card');
  await page.getByLabel(tr("Institution name")).fill('Manual');
  await page.getByLabel(tr("Last four digits (optional)")).fill('1234');
  await page.screenshot({ path: 'test-results/account-dialog-desktop.png', fullPage: false, animations: 'disabled' });
  await page.getByRole('button', { name: tr("Add account"), exact: true }).click();
  await expect(page.getByRole('dialog')).toHaveCount(0);
  await page.getByRole('button', { name: tr("Add transaction") }).click();
  await page.getByLabel(tr("Description"), { exact: true }).fill('Tokyo dinner');
  await page.getByLabel(tr("Amount (USD)")).fill('100.00');
  await selectOption(page.getByLabel(tr("Categories"), { exact: true }), 'dining');
  await selectOption(page.getByLabel(tr("Country"), { exact: true }), 'JP');
  await page.getByRole('button', { name: tr("Save transaction") }).click();
  await expect(page.getByRole('button', { name: new RegExp(tr("Total spending")) })).toContainText('$100.00');
  await page.getByLabel(tr("Filter descriptions"), { exact: true }).click();
  await page.getByLabel(tr("Filter description keywords")).fill('absent');
  await page.screenshot({ path: 'test-results/column-filter-desktop.png', fullPage: true, animations: 'disabled' });
  await page.getByLabel(tr("Filter descriptions"), { exact: true }).click();
  await expect(page.getByText(tr("No records match these filters"))).toBeVisible();
  await page.getByRole('button', { name: tr("Clear filters") }).click();
  await page.getByRole('button', { name: tr("Split {p0}", { p0: "Tokyo dinner" }) }).click();
  await page.getByLabel(tr("Amount (USD)")).fill('70.00');
  await page.getByRole('button', { name: tr("Add split") }).click();
  await selectOption(page.getByLabel(tr("Categories"), { exact: true }).nth(1), 'shopping');
  await page.getByRole('button', { name: tr("Save split") }).click();
  await expect(page.locator('tbody tr')).toHaveCount(2);
  await page.reload();
  await expect(page.locator('tbody tr')).toHaveCount(2);
  await expect(page.getByRole('button', { name: new RegExp(tr("Total spending")) })).toContainText('$100.00');
  await page.getByRole('button', { name: new RegExp(tr("Total income")) }).click();
  await expect(page.getByText(tr("No income records this month"))).toBeVisible();
  await page.setViewportSize({ width: 390, height: 844 });
  await page.screenshot({ path: 'test-results/accounting-mobile.png', fullPage: true, animations: 'disabled' });
  const overflow = await page.evaluate(() => ({ width: document.documentElement.scrollWidth, viewport: window.innerWidth, elements: [...document.querySelectorAll('body *')].filter((el) => el.getBoundingClientRect().right > window.innerWidth).map((el) => [el.tagName, el.className, el.getBoundingClientRect().right, getComputedStyle(el).position]) }));
  expect(overflow.width, JSON.stringify(overflow)).toBeLessThanOrEqual(overflow.viewport);
  // Month buttons remain usable on narrow screens and preserve the transaction mode.
  await page.getByRole('navigation', { name: tr("Month navigation") }).getByRole('button', { name: new RegExp("^" + shortMonth("2026-07", "zh") + " ") }).click();
  await expect(page.getByRole('heading', { name: tr("{p0}-{p1}", { p0: "2026", p1: "7" }) })).toBeVisible();
  expect(new URL(page.url()).searchParams.get('mode')).toBe('income');
  await page.getByRole('navigation', { name: tr("Month navigation") }).getByRole('button', { name: new RegExp("^" + shortMonth("2026-08", "zh") + " ") }).click();
  await page.setViewportSize({ width: 320, height: 740 });
  await expect(page.getByRole('button', { name: tr("Add transaction") })).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(320);
  await page.screenshot({ path: 'test-results/accounting-narrow.png', fullPage: true, animations: 'disabled' });
  await page.getByRole('button', { name: tr("Add transaction") }).click();
  await expect(page.getByLabel(tr("Description"), { exact: true })).toBeVisible();
  await page.screenshot({ path: 'test-results/transaction-dialog-mobile.png', fullPage: false, animations: 'disabled' });
  await page.getByRole('button', { name: tr("Cancel"), exact: true }).click();
  await expect(page.getByRole('dialog')).toHaveCount(0);
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.getByRole('button', { name: new RegExp(tr("Total spending")) }).click();
  await expect(page.locator('tbody tr')).toHaveCount(2);
  await page.screenshot({ path: 'test-results/accounting-desktop.png', fullPage: true, animations: 'disabled' });
  const accounts = await (await page.request.get('/api/accounts')).json();
  const accountId = accounts.find((account: { name: string }) => account.name === 'Browser test card').id;
  expect((await page.request.post('/api/transactions/manual', { data: { accountId, postedDate: '2026-08-02', description: 'Toggle fixture income', amount: '25', kind: 'income', category: 'salary', country: 'JP' } })).ok()).toBe(true);
  await page.goto(`/?month=2026-08&accounts=${accountId}&countries=JP&categories=dining&q=Tokyo&min=1&max=100&from=2026-08-01&to=2026-08-31&mode=expense&page=2`);
  const spending = page.getByRole('button', { name: new RegExp(tr('Total spending')) });
  await expect(spending).toHaveAttribute('aria-pressed', 'true');
  await expect(page.locator('tbody')).not.toContainText('Toggle fixture income');
  await spending.click();
  await expect(spending).toHaveAttribute('aria-pressed', 'false');
  await expect(page.locator('tbody')).toContainText('Toggle fixture income');
  expect(new URL(page.url()).searchParams.get('accounts')).toBe(accountId);
  expect(new URL(page.url()).searchParams.get('month')).toBe('2026-08');
  for (const key of ['q', 'categories', 'countries', 'from', 'to', 'min', 'max', 'page']) expect(new URL(page.url()).searchParams.has(key)).toBe(false);
  await expect(page.getByText(tr('Filters applied'), { exact: true })).toHaveCount(0);
  await expect(spending).not.toHaveClass(/selected/);
  await page.reload();
  await expect(spending).toHaveAttribute('aria-pressed', 'false');
  await expect(page.locator('tbody')).toContainText('Toggle fixture income');
  await spending.click();
  await expect(spending).toHaveAttribute('aria-pressed', 'true');
  await expect(page.locator('tbody')).not.toContainText('Toggle fixture income');
  await expect(page.locator('tbody')).toContainText('Tokyo dinner');
  const income = page.getByRole('button', { name: new RegExp(tr('Total income')) });
  await income.click();
  await expect(income).toHaveAttribute('aria-pressed', 'true');
  await expect(page.locator('tbody tr')).toHaveCount(1);
  await page.goto(`/?month=2026-08&accounts=${accountId}&mode=income&categories=salary&countries=JP&q=Toggle&page=2`);
  await income.click();
  await expect(income).toHaveAttribute('aria-pressed', 'false');
  await expect(page.locator('tbody tr')).toHaveCount(3);
  await expect(page.getByText(tr('Filters applied'), { exact: true })).toHaveCount(0);

  const breakdown = page.getByRole('region', { name: tr('Spending by category'), exact: true });
  const dining = breakdown.getByRole('link', { name: new RegExp(tr('Dining')) });
  await dining.click();
  await expect(dining).toHaveAttribute('aria-current', 'true');
  await expect(dining).toHaveClass(/selected/);
  await expect(page.locator('tbody tr')).toHaveCount(1);
  await page.goto(`/?month=2026-08&accounts=${accountId}&mode=expense&categories=dining&countries=JP&q=Tokyo&page=2`);
  await expect(dining).toHaveAttribute('aria-current', 'true');
  await breakdown.screenshot({ path: 'test-results/selected-category-card.png', animations: 'disabled' });
  await dining.press('Enter');
  await expect(dining).not.toHaveAttribute('aria-current', 'true');
  await expect(spending).toHaveAttribute('aria-pressed', 'false');
  await expect(page.locator('tbody tr')).toHaveCount(3);
  await expect(page.getByText(tr('Filters applied'), { exact: true })).toHaveCount(0);
  expect(new URL(page.url()).searchParams.get('accounts')).toBe(accountId);
  expect(new URL(page.url()).searchParams.get('month')).toBe('2026-08');
  await page.reload();
  await expect(dining).not.toHaveClass(/selected/);
  await expect(page.locator('tbody tr')).toHaveCount(3);
  expect(errors).toEqual([]);
});
