import { selectOption } from './select.js';
import { translate, shortMonth } from '../../src/i18n/index.js';
const tr = (key: string, params?: Record<string, string | number>) => translate('zh', key, params);
import { test, expect } from '@playwright/test';

test('Link callback, bank sync, classification, edits, cached history and investment income', async ({ page }) => {
  const errors: string[] = []; page.on('pageerror', (error) => errors.push(error.message));
  // Only the provider surface is synthetic; every local UI/API/storage/job operation is real.
  await page.route('https://cdn.plaid.com/link/v2/stable/link-initialize.js', (route) => route.fulfill({ contentType: 'application/javascript', body: `window.Plaid = { create(config) { return { open() { const investment = config.token === 'fixture-invest-link' || window.fixtureInvestment; config.onSuccess(investment ? 'fixture-invest-public' : 'fixture-bank-public', { institution: { name: investment ? 'Fidelity' : 'Chase' }, accounts: [{ id: investment ? 'invest-account' : 'bank-account', name: investment ? 'Fictional Fidelity investment' : 'Fictional Chase checking', mask: investment ? '2026' : '1827', type: investment ? 'investment' : 'depository' }] }); }, exit() {}, destroy() {} }; } };` }));
  await page.goto('/settings');
  await page.getByRole('button', { name: tr("Connect accounts"), exact: true }).click();
  await expect(page.getByText('Fictional Chase checking', { exact: true }).first()).toBeVisible();
  await expect(page.getByText(tr("Ledger updated."), { exact: true })).toBeVisible({ timeout: 10000 });
  await page.goto('/?month=2026-08');
  await selectOption(page.getByLabel(tr("Filter accounts")), { label: 'Fictional Chase checking · 1827' });
  await expect(page.getByRole('button', { name: new RegExp(tr("Total spending")) })).toContainText('$100.00');
  await expect(page.getByRole('button', { name: new RegExp(tr("Total income")) })).toContainText('$5,000.00');
  await expect(page.locator('tbody').getByText(tr("Japan"), { exact: true })).toBeVisible();
  const category = page.getByRole('combobox', { name: tr("Change category for {p0}", { p0: "Tokyo cafe" }), exact: true });
  await selectOption(category, 'shopping');
  await expect(category).toBeEnabled();
  await expect(category).toHaveAttribute('data-value', 'shopping');
  await expect(page.locator('tbody').getByText(tr("Japan"), { exact: true })).toBeVisible();
  await expect(page.getByRole('dialog')).toHaveCount(0);
  await page.getByRole('button', { name: tr("Edit {p0}", { p0: "Tokyo cafe" }), exact: true }).click();
  await selectOption(page.getByLabel(tr("Categories"), { exact: true }), 'groceries');
  await selectOption(page.getByLabel(tr("Country"), { exact: true }), 'CN');
  await page.getByRole('button', { name: tr("Save transaction") }).click();
  await expect(page.locator('tbody').getByText(tr("China"), { exact: true })).toBeVisible();
  await selectOption(category, 'health');
  await expect(category).toBeEnabled();
  await expect(category).toHaveAttribute('data-value', 'health');
  await page.getByRole('button', { name: tr("Sync bank data"), exact: true }).click();
  await expect(page.getByLabel(tr("Synchronization month"))).toHaveValue('2026-08');
  const monthlySync = page.waitForRequest((request) => request.url().endsWith('/api/jobs') && request.method() === 'POST');
  await page.getByRole('button', { name: tr("Start synchronization"), exact: true }).click();
  expect((await monthlySync).postDataJSON().range).toEqual({ start: '2026-08-01', end: '2026-08-31' });
  await expect(page.getByRole('dialog')).toHaveCount(0);
  await expect.poll(async () => (await (await page.request.get('/api/jobs')).json())[0].status).toBe('succeeded');
  await selectOption(page.getByLabel(tr('Select year'), { exact: true }), '2025');
  const monthNavigation = page.getByRole('navigation', { name: tr('Month navigation') });
  await expect(monthNavigation.getByRole('button')).toHaveCount(12);
  await monthNavigation.getByRole('button', { name: new RegExp('^' + shortMonth('2025-01', 'zh') + ' ') }).click();
  await expect(page.getByText(tr('No records this month'), { exact: true })).toBeVisible();
  await page.getByRole('button', { name: tr('Sync bank data'), exact: true }).click();
  await expect(page.getByLabel(tr('Synchronization month'))).toHaveValue('2025-01');
  const emptyMonthSync = page.waitForRequest((request) => request.url().endsWith('/api/jobs') && request.method() === 'POST');
  await page.getByRole('button', { name: tr('Start synchronization'), exact: true }).click();
  expect((await emptyMonthSync).postDataJSON().range).toEqual({ start: '2025-01-01', end: '2025-01-31' });
  await expect(page.getByRole('dialog')).toHaveCount(0);
  await expect.poll(async () => (await (await page.request.get('/api/jobs')).json())[0].status).toBe('succeeded');
  await page.getByRole('button', { name: tr('Sync bank data'), exact: true }).click();
  await page.getByRole('button', { name: tr('Date range'), exact: true }).click();
  await page.getByLabel(tr('Start date'), { exact: true }).fill('2024-11-01');
  await page.getByLabel(tr('End date'), { exact: true }).fill('2025-02-28');
  const widerSync = page.waitForRequest((request) => request.url().endsWith('/api/jobs') && request.method() === 'POST');
  await page.getByRole('button', { name: tr('Start synchronization'), exact: true }).click();
  expect((await widerSync).postDataJSON().range).toEqual({ start: '2024-11-01', end: '2025-02-28' });
  await expect(page.getByRole('dialog')).toHaveCount(0);
  await expect.poll(async () => (await (await page.request.get('/api/jobs')).json())[0].status).toBe('succeeded');
  await page.goto('/?month=2026-08');
  await selectOption(page.getByLabel(tr('Filter accounts')), { label: 'Fictional Chase checking · 1827' });
  await page.getByRole('button', { name: tr("Sync bank data"), exact: true }).click();
  await page.getByRole('button', { name: tr("Year"), exact: true }).click();
  await page.getByLabel(tr("Synchronization year")).fill('2025');
  await page.screenshot({ path: 'test-results/sync-dialog-desktop.png', animations: 'disabled' });
  await page.getByRole('button', { name: tr("Start synchronization"), exact: true }).click();
  await expect.poll(async () => (await (await page.request.get('/api/jobs')).json())[0].status).toBe('succeeded');
  await page.reload();
  await expect(page.locator('tbody').getByText(tr("China"), { exact: true })).toBeVisible();
  await expect(category).toHaveAttribute('data-value', 'health');
  await selectOption(page.getByLabel(tr("Select year"), { exact: true }), '2025');
  await expect(page.getByRole('button', { name: new RegExp(shortMonth("2025-10", "zh")) })).toBeVisible();
  await page.getByRole('button', { name: new RegExp(shortMonth("2025-10", "zh")) }).click();
  await expect(page.getByRole('button', { name: new RegExp(tr("Total spending")) })).toContainText('$5.00');
  await page.goto('/settings');
  await page.evaluate(() => Object.assign(window, { fixtureInvestment: true }));
  await page.getByRole('button', { name: tr('Connect accounts'), exact: true }).click();
  await expect(page.getByRole('dialog').getByText('Chase', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: tr('Connect another institution'), exact: true }).click();
  await expect(page.getByText('Fictional Fidelity investment', { exact: true }).first()).toBeVisible();
  await expect.poll(async () => (await (await page.request.get('/api/jobs')).json())[0].status).toBe('succeeded');
  await page.goto('/?month=2026-08&mode=income');
  await selectOption(page.getByLabel(tr("Filter accounts")), { label: 'Fictional Fidelity investment · 2026' });
  await expect(page.getByRole('button', { name: new RegExp(tr("Total income")) })).toContainText('$50.00');
  await expect(page.getByText('Fictional cash dividend', { exact: true })).toBeVisible();
  expect(errors).toEqual([]);
  await page.goto('/settings');
  const accountsTable = page.getByRole('table', { name: tr('My accounts'), exact: true });
  const connectionsTable = page.getByRole('table', { name: tr('Bank connections'), exact: true });
  await expect(accountsTable).toContainText('Fictional Chase checking');
  await expect(accountsTable).toContainText('Fictional Fidelity investment');
  await expect(connectionsTable.getByText('Chase', { exact: true })).toHaveCount(1);
  await expect(page.locator('.account-item, .connection-actions')).toHaveCount(0);
  const institutionHeader = accountsTable.getByRole('columnheader', { name: tr('Institution name') });
  await expect(institutionHeader).toHaveAttribute('aria-sort', 'ascending');
  await institutionHeader.getByRole('button').click();
  await expect(institutionHeader).toHaveAttribute('aria-sort', 'descending');
  // Other scenarios may have created manual accounts; check the relative order
  // of the two institutions connected by this scenario.
  await expect(accountsTable.locator('tbody tr').filter({ hasText: /Fictional (Chase|Fidelity)/ }).first()).toContainText('Fidelity');
  await institutionHeader.getByRole('button').click();
  const enabled = accountsTable.getByRole('switch', { name: tr('Enable {p0}', { p0: 'Fictional Chase checking' }), exact: true });
  await enabled.click();
  await expect(enabled).toHaveAttribute('aria-checked', 'false');
  await page.reload();
  await expect(enabled).toHaveAttribute('aria-checked', 'false');
  await enabled.click();
  await expect(enabled).toHaveAttribute('aria-checked', 'true');
  const update = page.waitForRequest((request) => request.url().endsWith('/api/plaid/link-token') && request.method() === 'POST');
  await page.getByRole('button', { name: tr('Manage accounts at {p0}', { p0: 'Fidelity' }), exact: true }).click();
  expect((await update).postDataJSON()).toEqual({ connectionId: 'invest-item' });
  await expect(page.getByText(tr('Ledger updated.'), { exact: true })).toBeVisible({ timeout: 10000 });
  const status = await (await page.request.get('/api/settings/status')).json();
  expect(status.connections).toHaveLength(2);
  await page.screenshot({ path: 'test-results/settings-desktop.png', fullPage: true, animations: 'disabled' });
  await page.locator('#bank-connections').screenshot({ path: 'test-results/settings-connections-desktop.png', animations: 'disabled' });
  await page.locator('#accounts').screenshot({ path: 'test-results/settings-accounts-desktop.png', animations: 'disabled' });
  await page.setViewportSize({ width: 390, height: 844 });
  await page.getByRole('link', { name: tr('Accounting'), exact: true }).click();
  await expect(page.getByRole('button', { name: tr("Add transaction") })).toBeVisible();
  await page.getByRole('link', { name: tr("Settings"), exact: true }).click();
  await expect(page.getByRole('heading', { name: tr("Bank connections") })).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(390);
  await page.screenshot({ path: 'test-results/settings-mobile.png', fullPage: true, animations: 'disabled' });
  for (const width of [390, 320]) {
    await page.setViewportSize({ width, height: 844 });
    await page.locator('#accounts').screenshot({ path: `test-results/settings-accounts-${width}.png`, animations: 'disabled' });
    await page.locator('#bank-connections').screenshot({ path: `test-results/settings-connections-${width}.png`, animations: 'disabled' });
    expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(width);
    await page.locator('#bank-connections .account-table-scroll').evaluate(element => { element.scrollLeft = element.scrollWidth; });
    await expect(connectionsTable.getByRole('button', { name: tr('Manage accounts at {p0}', { p0: 'Fidelity' }) })).toBeInViewport();
  }
});
