import { selectOption } from './select.js';
import { test, expect } from '@playwright/test';
import { translate } from '../../src/i18n/index.js';

const zh = (key: string) => translate('zh', key);
test('switches all screens and API errors, persists the selection and keeps the ledger compact', async ({ page, request }, testInfo) => {
  const account = await (await request.post('/api/accounts/manual', { data: { name: 'Language fixture', institution: 'Test', type: 'cash', mask: '0910' } })).json();
  await request.post('/api/transactions/manual', { data: { accountId: account.id, postedDate: '2026-08-01', description: 'Language fixture purchase', amount: '12.34', kind: 'expense', category: 'childcare', country: 'US', notes: zh('Notes (optional)') } });
  const job = await (await request.post('/api/jobs', { data: { type: 'classify', accountIds: [account.id], range: { start: '2026-08-01', end: '2026-08-31' } } })).json();
  await expect.poll(async () => (await (await request.get('/api/jobs')).json()).find((entry: { id: string }) => entry.id === job.id)?.status).toBe('succeeded');
  await page.goto('/settings');
  await selectOption(page.getByRole('combobox', { name: zh('Language'), exact: true }), 'en');
  await expect(page.locator('html')).toHaveAttribute('lang', 'en');
  await expect(page.getByRole('heading', { name: 'Bank connections', exact: true })).toBeVisible();
  await page.reload();
  await expect(page.getByRole('combobox', { name: 'Language', exact: true })).toHaveAttribute('data-value', 'en');
  await page.goto(`/?month=2026-08&accounts=${account.id}`);
  await expect(page.getByRole('button', { name: /Total spending/ })).toContainText('$12.34');
  await expect(page.getByRole('combobox', { name: 'Change category for Language fixture purchase' })).toHaveAttribute('data-value', 'childcare');
  const category = page.getByRole('region', { name: 'Spending by category', exact: true });
  const overview = page.getByRole('region', { name: 'This month', exact: true });
  const categoryBox = (await category.boundingBox())!; const overviewBox = (await overview.boundingBox())!;
  expect(Math.abs(categoryBox.y - overviewBox.y)).toBeLessThan(2);
  expect(overviewBox.x + overviewBox.width).toBeLessThan(categoryBox.x);
  expect(categoryBox.height).toBeLessThan(350);
  expect(Math.abs(overviewBox.height - categoryBox.height)).toBeLessThan(2);
  await page.getByRole('button', { name: /Total income/ }).click();
  await expect(page.getByText('No income records this month', { exact: true })).toBeVisible();
  await expect(category).toBeVisible();
  await expect(category.getByRole('link', { name: /Childcare/ })).toContainText('100%');
  expect((await category.boundingBox())!.y).toBe(categoryBox.y);
  expect(Math.abs((await overview.boundingBox())!.height - (await category.boundingBox())!.height)).toBeLessThan(2);
  await page.getByRole('button', { name: /Total spending/ }).click();
  await expect(page.locator('tbody')).toContainText('Language fixture purchase');
  const success = page.locator('.heading-actions .sync-success');
  await expect(success).toHaveText('Ledger updated.');
  const successBox = (await success.boundingBox())!;
  const syncBox = (await page.getByRole('button', { name: 'Sync bank data', exact: true }).boundingBox())!;
  expect(successBox.x + successBox.width).toBeLessThanOrEqual(syncBox.x);
  await page.screenshot({ path: testInfo.outputPath('accounting-en-desktop.png'), fullPage: true });
  await page.getByRole('button', { name: 'Sync bank data', exact: true }).click();
  await expect(page.getByRole('dialog', { name: 'Update ledger' })).toBeVisible();
  await expect(page.getByLabel('Synchronization month', { exact: true })).toHaveValue('2026-08');
  await page.getByRole('button', { name: 'Reclassify', exact: true }).click();
  await page.getByRole('button', { name: 'Date range', exact: true }).click();
  await page.getByLabel('Start date', { exact: true }).fill('2026-08-10');
  await page.getByLabel('End date', { exact: true }).fill('2026-01-01');
  const outgoing = page.waitForRequest((request) => request.url().endsWith('/api/jobs') && request.method() === 'POST');
  await page.getByRole('button', { name: 'Start classification', exact: true }).click();
  expect((await outgoing).headers()['accept-language']).toBe('en');
  await expect(page.getByRole('alert')).toContainText('The start date cannot be after the end date');
  await expect(page.getByRole('heading', { name: 'Update ledger' })).toBeVisible();
  await page.getByRole('button', { name: 'Close', exact: true }).click();
  await page.getByRole('button', { name: 'Edit Language fixture purchase', exact: true }).click();
  await expect(page.getByLabel('Notes (optional)')).toHaveValue(zh('Notes (optional)'));
  await page.getByRole('button', { name: 'Cancel', exact: true }).click();
  const apiFailure = await page.evaluate(async () => (await fetch('/api/transactions/missing', { headers: { 'Accept-Language': localStorage.getItem('respect-money-language') || '' } })).json());
  expect(apiFailure.error).toBe('Transaction not found.');
  await page.getByRole('link', { name: 'Overview', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Overview', exact: true })).toBeVisible();
  await page.getByRole('link', { name: 'Settings', exact: true }).click();
  await selectOption(page.getByRole('combobox', { name: 'Language', exact: true }), 'zh');
  await expect(page.getByRole('heading', { name: zh('Bank connections'), exact: true })).toBeVisible();
  await page.goto(`/?month=2026-08&accounts=${account.id}`);
  await expect(page.getByRole('button', { name: new RegExp(zh('Total spending')) })).toContainText('$12.34');
  await page.setViewportSize({ width: 390, height: 844 });
  await page.screenshot({ path: testInfo.outputPath('accounting-zh-mobile.png'), fullPage: true });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.goto('/settings');
  await selectOption(page.getByRole('combobox', { name: zh('Language'), exact: true }), 'en');
  await page.goto(`/?month=2026-08&accounts=${account.id}`);
  await expect(page.getByRole('button', { name: /Total spending/ })).toBeVisible();
  await page.screenshot({ path: testInfo.outputPath('accounting-en-mobile.png'), fullPage: true });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
});
