import { expect, test } from '@playwright/test';
import { selectOption } from './select.js';

test('themed menus support keyboard dismissal, long labels, modal forms and narrow screens', async ({ page, request }, testInfo) => {
  const errors: string[] = [];
  page.on('pageerror', (error) => errors.push(error.message));
  await page.addInitScript(() => localStorage.setItem('respect-money-language', 'en'));
  const accountName = 'Dropdown fixture with a deliberately long account name';
  const account = await (await request.post('/api/accounts/manual', { data: { name: accountName, institution: 'Test', type: 'cash', mask: '9382' } })).json();
  await page.goto('/?month=2026-08');
  const year = page.getByRole('combobox', { name: 'Select year', exact: true });
  await year.focus();
  await page.keyboard.press('ArrowDown');
  const menu = page.getByRole('listbox');
  await expect(menu).toBeVisible();
  await expect(page.getByRole('option', { selected: true })).toContainText('2026');
  await page.screenshot({ path: testInfo.outputPath('year-dropdown-desktop.png'), animations: 'disabled' });
  await page.keyboard.press('ArrowDown');
  await page.keyboard.press('Escape');
  await expect(year).toBeFocused();
  await expect(year).toHaveAttribute('data-value', '2026');
  await year.press('Enter');
  await expect(menu).toBeVisible();
  await page.keyboard.press('Home');
  await expect(page.getByRole('option', { name: '2026', exact: true })).toBeFocused();
  await page.keyboard.press('ArrowDown');
  await expect(page.getByRole('option', { name: '2025', exact: true })).toBeFocused();
  await page.keyboard.press('Enter');
  await expect(year).toHaveAttribute('data-value', '2025');
  await year.click();
  await page.mouse.click(10, 10);
  await expect(menu).toHaveCount(0);

  const accounts = page.getByRole('combobox', { name: 'Filter accounts', exact: true });
  await selectOption(accounts, account.id);
  await expect(accounts).toContainText('9382');
  await selectOption(accounts, '');
  await expect(accounts).toHaveText('All enabled accounts');

  await page.setViewportSize({ width: 320, height: 740 });
  await page.getByRole('button', { name: 'Add transaction', exact: true }).click();
  const dialog = page.getByRole('dialog');
  await selectOption(dialog.getByRole('combobox', { name: 'Account', exact: true }), account.id);
  await page.getByLabel('Description', { exact: true }).fill('Themed dropdown form fixture');
  await page.getByLabel('Amount (USD)', { exact: true }).fill('7.00');
  await selectOption(dialog.getByRole('combobox', { name: 'Categories', exact: true }), 'groceries');
  const country = dialog.getByRole('combobox', { name: 'Country', exact: true });
  await country.click();
  await expect(dialog.getByRole('listbox')).toBeVisible();
  const bounds = (await menu.boundingBox())!;
  expect(bounds.x).toBeGreaterThanOrEqual(0);
  expect(bounds.x + bounds.width).toBeLessThanOrEqual(320);
  expect(bounds.y).toBeGreaterThanOrEqual(0);
  expect(bounds.y + bounds.height).toBeLessThanOrEqual(740);
  await page.screenshot({ path: testInfo.outputPath('country-dropdown-mobile.png'), animations: 'disabled' });
  await page.keyboard.press('Escape');
  await expect(dialog).toBeVisible();
  await expect(country).toBeFocused();
  await country.press('Enter');
  await expect(menu).toBeVisible();
  await page.keyboard.type('Japan');
  await expect(page.getByRole('option', { name: 'Japan', exact: true })).toBeFocused();
  await page.keyboard.press('Enter');
  await expect(country).toHaveText('Japan');
  const saved = page.waitForRequest((request) => request.url().endsWith('/api/transactions/manual') && request.method() === 'POST');
  await page.getByRole('button', { name: 'Save transaction', exact: true }).click();
  expect((await saved).postDataJSON()).toMatchObject({ accountId: account.id, category: 'groceries', country: 'JP' });
  await expect(dialog).toHaveCount(0);
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(320);
  expect(errors).toEqual([]);
});
