import { test, expect } from '@playwright/test';
import { translate } from '../../src/i18n/index.js';
import { selectOption } from './select.js';

const tr = (key: string, params?: Record<string, string | number>) => translate('zh', key, params);
test('aggregates connected balances and supports property, vehicle and mobile asset editing', async ({ page, request }, testInfo) => {
  const pageErrors: string[] = []; page.on('pageerror', (error) => pageErrors.push(error.message));
  for (const product of ['transactions', 'investments']) {
    const session = await (await request.post('/api/plaid/link-token', { data: { product } })).json();
    expect((await request.post('/api/plaid/complete', { data: { sessionId: session.sessionId, publicToken: product === 'investments' ? 'fixture-invest-public' : 'fixture-bank-public', institution: product === 'investments' ? 'Fidelity' : 'Chase' } })).ok()).toBe(true);
  }
  await page.goto('/');
  await page.getByRole('navigation', { name: tr('Main navigation') }).getByRole('link', { name: tr('Wealth'), exact: true }).click();
  await expect(page).toHaveURL(/\/wealth$/);
  // Reconnected fixture accounts may retain an earlier refresh timestamp from
  // the disconnect scenario. Refresh explicitly before checking their balances.
  await page.getByRole('button', { name: tr('Update balances'), exact: true }).click();
  await expect(page.getByTestId('total-assets')).toHaveText(/87,500$/);
  await expect(page.getByTestId('total-assets-converted')).toContainText('586,250');
  await expect(page.getByRole('region', { name: tr('Asset allocation'), exact: true }).locator('.allocation-list')).toContainText(tr('Investment account'));
  await expect(page.getByRole('region', { name: tr('Asset allocation'), exact: true }).locator('.allocation-list')).toContainText('85.7%');
  const wealthNav = page.getByRole('navigation', { name: tr('Wealth sections'), exact: true });
  const overviewLink = wealthNav.getByRole('link', { name: tr('Wealth'), exact: true });
  const accountLink = wealthNav.getByRole('link', { name: tr('Account balances'), exact: true });
  const historyLink = wealthNav.getByRole('link', { name: tr('Balance history'), exact: true });
  await expect(wealthNav.getByRole('link')).toHaveCount(3);
  await expect(overviewLink).toHaveAttribute('aria-current', 'page');
  const balances = page.locator('.wealth-balances').getByRole('table');
  await expect(balances).not.toBeVisible();
  await page.getByRole('button', { name: tr('Add asset'), exact: true }).first().click();
  await page.getByLabel(tr('Asset name'), { exact: true }).fill('Fixture home');
  await page.getByLabel(tr('Property address (optional)'), { exact: true }).fill('123 Example Street');
  await expect(page.getByRole('link', { name: tr('Open Redfin Estimate') })).toHaveAttribute('href', 'https://www.redfin.com/redfin-estimate');
  await page.getByLabel(tr('Estimated value (USD)'), { exact: true }).fill('800000');
  await page.getByLabel(tr('Mortgage balance (USD)'), { exact: true }).fill('500000');
  await expect(page.locator('.wealth-equity-preview')).toContainText('300,000.00');
  await page.getByRole('button', { name: tr('Save asset'), exact: true }).click();
  await expect(page.getByRole('dialog')).toHaveCount(0);
  await expect(page.getByTestId('net-worth')).toHaveText(/387,500$/);
  await page.getByRole('button', { name: tr('Add asset'), exact: true }).click();
  await selectOption(page.getByLabel(tr('Asset type'), { exact: true }), 'vehicle');
  await page.getByLabel(tr('Asset name'), { exact: true }).fill('Fixture car');
  await page.getByLabel(tr('Vehicle brand and model'), { exact: true }).fill('Toyota RAV4 2022');
  await page.getByLabel(tr('Estimated value (USD)'), { exact: true }).fill('25000');
  await page.getByLabel(tr('Outstanding debt (USD)'), { exact: true }).fill('5000');
  await page.getByRole('button', { name: tr('Save asset'), exact: true }).click();
  await expect(page.getByTestId('net-worth')).toHaveText(/407,500$/);
  await expect(page.getByTestId('net-worth-converted')).toContainText('2,730,250');
  const allocation = page.getByRole('region', { name: tr('Asset allocation'), exact: true });
  const debtAllocation = page.getByRole('region', { name: tr('Debt allocation'), exact: true });
  await expect(debtAllocation).toContainText(tr('Mortgages'));
  await expect(debtAllocation).toContainText('99.0%');
  await expect(debtAllocation).toContainText(tr('Vehicle loans'));
  await page.getByRole('button', { name: tr('Asset details'), exact: true }).click();
  let details = page.getByRole('dialog');
  await expect(details).toContainText('912,500');
  await expect(details.getByRole('table').getByRole('row')).toHaveCount(5);
  await expect(details).toContainText('Fictional Fidelity investment');
  await expect(details).toContainText('Fixture home');
  await details.getByRole('button', { name: tr('Close'), exact: true }).click();
  await allocation.getByRole('button', { name: tr('View {p0} details', { p0: tr('Investment account') }), exact: true }).click();
  details = page.getByRole('dialog');
  await expect(details.getByRole('table').getByRole('row')).toHaveCount(2);
  await expect(details).toContainText('75,000');
  await expect(details).not.toContainText('Fixture home');
  await page.keyboard.press('Escape');
  await page.getByRole('button', { name: tr('Net worth details'), exact: true }).click();
  await expect(page.getByRole('dialog').getByRole('table')).toHaveCount(2);
  await page.keyboard.press('Escape');

  await expect(page.getByRole('article', { name: 'Fixture home' })).toContainText('5,360,000');
  await page.getByRole('link', { name: tr('1 USD = {rate} {currency}', { rate: 6.7, currency: 'CNY' }), exact: true }).click();
  await expect(page.getByLabel(tr('Exchange rate per 1 USD'))).toHaveValue('6.7');
  await page.getByLabel(tr('Exchange rate per 1 USD')).fill('7');
  await page.locator('#currency').getByRole('button', { name: tr('Save settings'), exact: true }).click();
  await expect(page.getByText(tr('Settings saved. Future tasks will use the new configuration.'), { exact: true })).toBeVisible();
  await page.reload();
  await expect(page.getByLabel(tr('Exchange rate per 1 USD'))).toHaveValue('7');
  await page.goto('/wealth');
  await expect(page.getByTestId('net-worth')).toHaveText(/407,500$/);
  await expect(page.getByTestId('net-worth-converted')).toContainText('2,852,500');
  await expect(page.getByRole('article', { name: 'Fixture home' })).toContainText('5,600,000');
  await page.reload();
  await expect(page.getByRole('article', { name: 'Fixture car' })).toContainText('Toyota RAV4 2022');
  await historyLink.click();
  await expect(page).toHaveURL(/\/wealth\/history$/);
  await page.reload();
  await expect(historyLink).toHaveAttribute('aria-current', 'page');
  await expect(page.getByRole('heading', { name: tr('Balance history'), exact: true })).toBeVisible();
  await page.getByRole('button', { name: tr('Update balances'), exact: true }).click();
  await expect(page.getByRole('table', { name: tr('Historical manual assets'), exact: true })).toContainText('Fixture car');
  await expect(page.locator('.wealth-history-totals')).toContainText('407,500');
  await expect(page.getByRole('table', { name: tr('Historical account balances'), exact: true })).toContainText('Fictional Chase checking');
  await overviewLink.click();
  await expect(page.getByTestId('net-worth')).toBeVisible();
  await page.evaluate(() => document.fonts.ready);
  for (const width of [1440, 390, 320]) {
    await page.setViewportSize({ width, height: width > 760 ? 1000 : 844 });
    expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(width);
    await page.screenshot({ path: testInfo.outputPath(`wealth-${width}.png`), fullPage: true });
    const allocationBounds = (await allocation.boundingBox())!;
    const debtBounds = (await debtAllocation.boundingBox())!;
    const manualArea = (await page.getByRole('region', { name: tr('Manual assets'), exact: true }).boundingBox())!;
    expect(manualArea.y).toBeGreaterThanOrEqual(Math.max(allocationBounds.y + allocationBounds.height, debtBounds.y + debtBounds.height));
    if (width === 1440) { expect(debtBounds.x).toBeGreaterThan(allocationBounds.x); expect(debtBounds.height).toBe(allocationBounds.height); }
    await page.getByRole('button', { name: tr('Debt details'), exact: true }).click();
    await expect(page.getByRole('dialog')).toContainText('505,000');
    await expect(page.getByRole('dialog').getByRole('table').getByRole('row')).toHaveCount(3);
    await page.screenshot({ path: testInfo.outputPath(`debt-details-${width}.png`), animations: 'disabled' });
    const detailBounds = (await page.getByRole('dialog').boundingBox())!;
    expect(detailBounds.x).toBeGreaterThanOrEqual(0); expect(detailBounds.x + detailBounds.width).toBeLessThanOrEqual(width);
    await page.keyboard.press('Escape');
    await debtAllocation.getByRole('button', { name: tr('View {p0} details', { p0: tr('Vehicle loans') }), exact: true }).click();
    await expect(page.getByRole('dialog')).toContainText('Fixture car');
    await expect(page.getByRole('dialog')).not.toContainText('Fixture home');
    await page.keyboard.press('Escape');

    await historyLink.click();
    await expect(page.getByLabel(tr('Snapshot date (Pacific)'))).toBeVisible();
    expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(width);
    await page.screenshot({ path: testInfo.outputPath(`balance-history-${width}.png`), fullPage: true });
    await accountLink.focus(); await page.keyboard.press('Enter');
    await expect(page).toHaveURL(/\/wealth\/accounts$/);
    await expect(accountLink).toHaveAttribute('aria-current', 'page');
    await expect(page.getByRole('navigation', { name: tr('Main navigation') }).getByRole('link', { name: tr('Wealth'), exact: true })).toHaveAttribute('aria-current', 'page');
    await expect(page.getByTestId('net-worth')).toHaveCount(0);
    await expect(page.locator('.wealth-history')).toHaveCount(0);
    await page.reload();
    await expect(page.getByRole('heading', { name: tr('Account balances'), exact: true })).toBeVisible();
    await expect(balances).toBeVisible();
    await expect(balances.getByRole('row')).toHaveCount(3);
    expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(width);
    await page.screenshot({ path: testInfo.outputPath(`account-balances-${width}.png`), fullPage: true });
    await overviewLink.click(); await expect(balances).toHaveCount(0);
    await page.getByRole('button', { name: tr('Edit {p0}', { p0: 'Fixture home' }), exact: true }).click();
    await expect(page.getByLabel(tr('Mortgage balance (USD)'), { exact: true })).toHaveValue('500000.00');
    const bounds = (await page.getByRole('dialog').boundingBox())!;
    expect(bounds.x).toBeGreaterThanOrEqual(0); expect(bounds.x + bounds.width).toBeLessThanOrEqual(width);
    await page.screenshot({ path: testInfo.outputPath(`property-form-${width}.png`), fullPage: false });
    if (width === 320) {
      await page.getByLabel(tr('Mortgage balance (USD)'), { exact: true }).fill('480000');
      await page.getByRole('button', { name: tr('Save asset'), exact: true }).click();
      await expect(page.getByTestId('net-worth')).toHaveText(/427,500$/);
    } else await page.getByRole('button', { name: tr('Cancel'), exact: true }).click();
  }
  await accountLink.click();
  await expect(balances.getByRole('checkbox')).toHaveCount(0);
  await page.goBack();
  await expect(overviewLink).toHaveAttribute('aria-current', 'page');
  await page.getByRole('button', { name: tr('Remove {p0}', { p0: 'Fixture car' }), exact: true }).click();
  await page.getByRole('button', { name: tr('Remove asset'), exact: true }).click();
  await expect(page.getByRole('article', { name: 'Fixture car' })).toHaveCount(0);
  await page.goto('/settings');
  await selectOption(page.getByRole('combobox', { name: tr('Language'), exact: true }), 'en');
  await page.goto('/wealth');
  await expect(page.getByRole('heading', { name: 'Wealth', exact: true })).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(320);
  await page.screenshot({ path: testInfo.outputPath('wealth-en-320.png'), fullPage: true });
  await page.getByRole('navigation', { name: 'Wealth sections' }).getByRole('link', { name: 'Account balances', exact: true }).click();
  await expect(page).toHaveTitle('Respect Money · Account balances');
  await page.screenshot({ path: testInfo.outputPath('account-balances-en-320.png'), fullPage: true });
  await page.getByRole('navigation', { name: 'Wealth sections' }).getByRole('link', { name: 'Wealth', exact: true }).click();
  await page.getByRole('button', { name: 'Remove Fixture home', exact: true }).click();
  await page.getByRole('button', { name: 'Remove asset', exact: true }).click();
  await expect(page.getByRole('article', { name: 'Fixture home' })).toHaveCount(0);
  expect(pageErrors).toEqual([]);
});
